// Generated from reviewed inert data and original model; reproduce with scripts/build.mjs.
export const INPUTS = {
  "schema": "turnaround-frozen-inputs/1",
  "classification": "Synthetic seed facts plus explicitly separated added assumptions",
  "case": {
    "id": "cedarline-five-day-recovery",
    "business": "Cedarline Desk",
    "asOf": "2026-09-30",
    "months": [
      "2026-07",
      "2026-08",
      "2026-09"
    ],
    "openingCashCents": 5200000,
    "cashFloorCents": 1200000,
    "daysPerMonth": 30,
    "sprintWorkingDays": 5,
    "engineeringCapacityMinutes": 360,
    "supportCapacityMinutes": 420,
    "accountingAssumption": "All included plan billings are collected in the same month; ledger is cash-only and not a complete financial statement.",
    "payableTreatment": "Incremental unpaid prior-period catch-up obligations, not already paid in the ledger or included in recurring scenario outflows.",
    "approvedExternalEffects": [],
    "realizedRecoveryResults": null
  },
  "ledger": [
    {
      "id": "cash-jul-receipts",
      "date": "2026-07-31",
      "category": "subscription-receipts",
      "direction": "in",
      "amountCents": 1800000
    },
    {
      "id": "cash-jul-payroll",
      "date": "2026-07-28",
      "category": "payroll",
      "direction": "out",
      "amountCents": 1700000
    },
    {
      "id": "cash-jul-contractors",
      "date": "2026-07-29",
      "category": "contractors",
      "direction": "out",
      "amountCents": 300000
    },
    {
      "id": "cash-jul-hosting",
      "date": "2026-07-30",
      "category": "hosting",
      "direction": "out",
      "amountCents": 120000
    },
    {
      "id": "cash-jul-refunds",
      "date": "2026-07-31",
      "category": "refunds",
      "direction": "out",
      "amountCents": 80000
    },
    {
      "id": "cash-aug-receipts",
      "date": "2026-08-31",
      "category": "subscription-receipts",
      "direction": "in",
      "amountCents": 1600000
    },
    {
      "id": "cash-aug-payroll",
      "date": "2026-08-28",
      "category": "payroll",
      "direction": "out",
      "amountCents": 1700000
    },
    {
      "id": "cash-aug-contractors",
      "date": "2026-08-29",
      "category": "contractors",
      "direction": "out",
      "amountCents": 300000
    },
    {
      "id": "cash-aug-hosting",
      "date": "2026-08-30",
      "category": "hosting",
      "direction": "out",
      "amountCents": 140000
    },
    {
      "id": "cash-aug-refunds",
      "date": "2026-08-31",
      "category": "refunds",
      "direction": "out",
      "amountCents": 120000
    },
    {
      "id": "cash-sep-receipts",
      "date": "2026-09-30",
      "category": "subscription-receipts",
      "direction": "in",
      "amountCents": 1450000
    },
    {
      "id": "cash-sep-payroll",
      "date": "2026-09-28",
      "category": "payroll",
      "direction": "out",
      "amountCents": 1700000
    },
    {
      "id": "cash-sep-contractors",
      "date": "2026-09-29",
      "category": "contractors",
      "direction": "out",
      "amountCents": 300000
    },
    {
      "id": "cash-sep-hosting",
      "date": "2026-09-30",
      "category": "hosting",
      "direction": "out",
      "amountCents": 180000
    },
    {
      "id": "cash-sep-refunds",
      "date": "2026-09-30",
      "category": "refunds",
      "direction": "out",
      "amountCents": 170000
    }
  ],
  "subscriptions": [
    {
      "id": "2026-07-starter",
      "month": "2026-07",
      "plan": "starter",
      "accounts": 100,
      "priceCents": 10000
    },
    {
      "id": "2026-07-team",
      "month": "2026-07",
      "plan": "team",
      "accounts": 16,
      "priceCents": 50000
    },
    {
      "id": "2026-08-starter",
      "month": "2026-08",
      "plan": "starter",
      "accounts": 90,
      "priceCents": 10000
    },
    {
      "id": "2026-08-team",
      "month": "2026-08",
      "plan": "team",
      "accounts": 14,
      "priceCents": 50000
    },
    {
      "id": "2026-09-starter",
      "month": "2026-09",
      "plan": "starter",
      "accounts": 80,
      "priceCents": 10000
    },
    {
      "id": "2026-09-team",
      "month": "2026-09",
      "plan": "team",
      "accounts": 13,
      "priceCents": 50000
    }
  ],
  "payables": [
    {
      "id": "arrears-support",
      "dueOn": "2026-10-10",
      "amountCents": 250000,
      "basis": "Prior-period support catch-up obligation not in cash ledger",
      "treatment": "incremental-prior-period-reserve"
    },
    {
      "id": "arrears-hosting",
      "dueOn": "2026-10-05",
      "amountCents": 180000,
      "basis": "Prior-period hosting catch-up obligation not in cash ledger",
      "treatment": "incremental-prior-period-reserve"
    },
    {
      "id": "arrears-refunds",
      "dueOn": "2026-10-02",
      "amountCents": 120000,
      "basis": "Prior-period approved-in-fiction unpaid refunds not in cash ledger",
      "treatment": "incremental-prior-period-reserve"
    }
  ],
  "rates": [
    {
      "id": "repeat-september",
      "receiptsCents": 1450000,
      "payrollCents": 1700000,
      "contractorsCents": 300000,
      "hostingCents": 180000,
      "refundsCents": 170000,
      "precondition": "Mechanical repeat of September cash pattern; not a forecast commitment"
    },
    {
      "id": "bounded-containment",
      "receiptsCents": 1450000,
      "payrollCents": 1700000,
      "contractorsCents": 150000,
      "hostingCents": 160000,
      "refundsCents": 170000,
      "precondition": "Unapproved contractor allocation and hosting changes; evidence and owner review required"
    }
  ],
  "tickets": [
    {
      "id": "ticket-001",
      "openedOn": "2026-09-10",
      "priority": "urgent",
      "state": "open",
      "minutes": 90,
      "affectedAccounts": 7,
      "blockedBy": "",
      "issue": "Duplicate export acknowledgment in batch retry"
    },
    {
      "id": "ticket-002",
      "openedOn": "2026-09-06",
      "priority": "low",
      "state": "open",
      "minutes": 20,
      "affectedAccounts": 1,
      "blockedBy": "",
      "issue": "Misaligned export title in wide layout"
    },
    {
      "id": "ticket-003",
      "openedOn": "2026-09-15",
      "priority": "normal",
      "state": "open",
      "minutes": 60,
      "affectedAccounts": 3,
      "blockedBy": "",
      "issue": "Saved view sort resets on reopen"
    },
    {
      "id": "ticket-004",
      "openedOn": "2026-09-21",
      "priority": "urgent",
      "state": "open",
      "minutes": 120,
      "affectedAccounts": 5,
      "blockedBy": "needs-synthetic-reproduction",
      "issue": "Intermittent retry log cannot yet be reproduced"
    },
    {
      "id": "ticket-005",
      "openedOn": "2026-09-12",
      "priority": "normal",
      "state": "open",
      "minutes": 75,
      "affectedAccounts": 4,
      "blockedBy": "",
      "issue": "Bulk tag operation drops the visible selection"
    },
    {
      "id": "ticket-006",
      "openedOn": "2026-09-20",
      "priority": "low",
      "state": "open",
      "minutes": 25,
      "affectedAccounts": 1,
      "blockedBy": "",
      "issue": "Secondary button caption is unclear"
    },
    {
      "id": "ticket-007",
      "openedOn": "2026-09-25",
      "priority": "urgent",
      "state": "open",
      "minutes": 90,
      "affectedAccounts": 6,
      "blockedBy": "",
      "issue": "Retry status remains pending after acknowledged completion"
    },
    {
      "id": "ticket-008",
      "openedOn": "2026-09-27",
      "priority": "normal",
      "state": "open",
      "minutes": 45,
      "affectedAccounts": 2,
      "blockedBy": "",
      "issue": "Empty-list state omits a recovery hint"
    },
    {
      "id": "ticket-009",
      "openedOn": "2026-09-01",
      "priority": "low",
      "state": "open",
      "minutes": 15,
      "affectedAccounts": 1,
      "blockedBy": "",
      "issue": "Help icon baseline differs between two pages"
    },
    {
      "id": "ticket-010",
      "openedOn": "2026-09-18",
      "priority": "urgent",
      "state": "open",
      "minutes": 60,
      "affectedAccounts": 8,
      "blockedBy": "",
      "issue": "Urgent queue view shows no reason for skipped items"
    },
    {
      "id": "ticket-011",
      "openedOn": "2026-09-09",
      "priority": "normal",
      "state": "open",
      "minutes": 60,
      "affectedAccounts": 4,
      "blockedBy": "",
      "issue": "Filter summary disappears on back navigation"
    },
    {
      "id": "ticket-012",
      "openedOn": "2026-09-23",
      "priority": "low",
      "state": "open",
      "minutes": 30,
      "affectedAccounts": 1,
      "blockedBy": "",
      "issue": "Printed legend has an unnecessary blank row"
    }
  ],
  "sprint": [
    {
      "id": "sprint-reproduce",
      "owner": "engineering",
      "bucket": "engineering",
      "minutes": 60,
      "dependsOn": "",
      "entryGate": "Authored baseline and reviewed defect scope",
      "exitEvidence": "Minimal failing-policy reproduction"
    },
    {
      "id": "sprint-patch",
      "owner": "engineering",
      "bucket": "engineering",
      "minutes": 180,
      "dependsOn": "sprint-reproduce",
      "entryGate": "Agreed severity and exclusion rule",
      "exitEvidence": "Candidate module and narrow tests"
    },
    {
      "id": "sprint-regression",
      "owner": "operations",
      "bucket": "engineering",
      "minutes": 90,
      "dependsOn": "sprint-patch",
      "entryGate": "Candidate source available",
      "exitEvidence": "Actually run regression results"
    },
    {
      "id": "sprint-rollback",
      "owner": "operations",
      "bucket": "engineering",
      "minutes": 30,
      "dependsOn": "sprint-regression",
      "entryGate": "Regression findings reviewed",
      "exitEvidence": "Documented hold/rollback boundary"
    },
    {
      "id": "sprint-support",
      "owner": "operations",
      "bucket": "support",
      "minutes": 420,
      "dependsOn": "sprint-rollback",
      "entryGate": "Owner approval required before actual account work",
      "exitEvidence": "Prospective support slice; no completion implied"
    },
    {
      "id": "sprint-customer-review",
      "owner": "customer-success",
      "bucket": "review",
      "minutes": 60,
      "dependsOn": "sprint-regression",
      "entryGate": "Truthful drafts and commitment review",
      "exitEvidence": "Unsent reviewed message drafts"
    },
    {
      "id": "sprint-cash-review",
      "owner": "finance",
      "bucket": "review",
      "minutes": 60,
      "dependsOn": "",
      "entryGate": "Reconciled ledger and incremental reserve",
      "exitEvidence": "Conditional scenario review"
    }
  ],
  "approvalGates": {
    "classification": "SYNTHETIC",
    "default": "planning-only",
    "gates": [
      {
        "effect": "production-deployment",
        "required": [
          "candidate regression evidence",
          "rollback/hold procedure",
          "explicit owner approval"
        ],
        "approved": false
      },
      {
        "effect": "support-work-against-accounts",
        "required": [
          "reviewed ticket scope",
          "capacity and data-access review",
          "explicit owner approval"
        ],
        "approved": false
      },
      {
        "effect": "customer-message-or-refund-promise",
        "required": [
          "truthful draft",
          "financial commitment review",
          "explicit owner approval"
        ],
        "approved": false
      },
      {
        "effect": "contractor-or-hosting-cost-change",
        "required": [
          "service continuity review",
          "contract/cost evidence",
          "explicit owner approval"
        ],
        "approved": false
      },
      {
        "effect": "payment-trade-or-financing",
        "required": [
          "separate qualified review",
          "explicit owner authority"
        ],
        "approved": false
      }
    ],
    "reference_utility_effects": [],
    "warning": "A simulation or passing local test is not a financial instruction, completed support action, or approval."
  },
  "model": {
    "schema": "turnaround-assumptions/1",
    "classification": "ADDED MODEL ASSUMPTIONS, NOT SEED FACTS",
    "defaults": {
      "horizonDays": 90,
      "receiptDelayDays": 0,
      "demandBps": 10000,
      "acceleratedBps": 6500,
      "supportSliceMinutes": 300,
      "reviewCapacityMinutes": 180,
      "warningLeadDays": 7,
      "contractorConsent": true,
      "hostingValidated": true,
      "receiptConsent": true,
      "deferralConsent": true
    },
    "definitions": [
      {
        "id": "calendar",
        "text": "Day 1 is 2026-10-01. Horizon is 90 calendar days. Three normalized 30-day billing cycles are used, NOT actual calendar months. Work is Monday-Friday, no holidays; lead times are calendar days and start after the actual work start."
      },
      {
        "id": "billing",
        "text": "Repeat September's receipts and expenses, rather than extrapolating growth. Every cycle's payroll is due on offset 28, contractors on 29, and hosting/refunds/receipts on 30, using the seed posting pattern as a timing assumption. Outflows are due before same-day receipts."
      },
      {
        "id": "accounting",
        "text": "All money is integer cents. Scheduled cash equals opening bank cash plus scheduled receipts less required outflows. Negative scheduled cash is an unfunded requirement, never an authorized overdraft. The executable prefix ends at the first unfunded payment; all later events are explicitly counterfactual schedule arithmetic."
      },
      {
        "id": "reserve",
        "text": "Outstanding incremental prior-period payables stay reserved until their scheduled payment, even when deferred beyond the horizon. Cash-floor tests use scheduled cash less these reserves. A reserve release is not a receipt. Agreed deferral fees are also reserved immediately."
      },
      {
        "id": "floor",
        "text": "A strict value below $12,000 breaches the floor. Exactly $12,000 is not a breach; exactly zero bank cash can fund the preceding payment. Test every event including the trough before same-day receipts, not only daily closing cash."
      },
      {
        "id": "capacity",
        "text": "The seed's 360 engineering and 420 support minutes are single total budgets, never replenished weekly. Added daily caps are 120 engineering, 210 support and 90 review minutes. Review has an added 180-minute total budget. Splitting work evenly over an action's working days is a scheduling simplification, not a staff availability fact."
      },
      {
        "id": "action-outcomes",
        "text": "All actions are conditional and unapproved. Their one-time fees are paid at actual start and remain lost if consent/validation fails. Work time is consumed either way. No repair or support work automatically creates sales, retention or refund savings."
      },
      {
        "id": "cost-changes",
        "text": "Contractor and hosting levels come from the seed containment scenario. They apply only to a complete 30-day cycle starting on or after action readiness. Existing-cycle invoices are not reduced retrospectively."
      },
      {
        "id": "receipts",
        "text": "Collection coordination can move 65% of already-assumed cycle receipts from day 30 to day 20, only if ready by day 20 and assumed consent holds. It never increases the cycle total. All receipts, including accelerated portions, receive the same additional delay. Weaker demand reduces each cycle's existing receipts; no replacement sales or financing are permitted."
      },
      {
        "id": "deferral",
        "text": "Negotiating the $2,500 prior support payable before its due date can move it by 30 calendar days, with a $100 sunk negotiation fee, $125 added late fee and loss of 120 support minutes from the one-time budget. These are assumed consequences, not contract facts. Consent failure keeps the original due date and spends the negotiation fee without benefit."
      },
      {
        "id": "warning",
        "text": "All inputs are known in this deterministic exercise, so the earliest forecast warning is day 0 whenever any modeled future failure exists. The separate rolling escalation starts max(0, breach day minus warningLeadDays); it is a policy clock, not a prediction that the risk was unknowable earlier."
      },
      {
        "id": "support",
        "text": "Queue repair allocates the seed's 60+180+90+30 engineering minutes across three working days. The optional support slice is prospective, non-preemptive severity/age/ID fit over two working days after repair readiness. Tickets remain unexecuted. Unselected and blocked tickets stay visible; overlapping affected-account counts are never summed."
      }
    ],
    "dailyCapacity": {
      "engineering": 120,
      "support": 210,
      "review": 90
    },
    "actions": [
      {
        "id": "queue-repair",
        "title": "Review & repair queue",
        "description": "Reserve the authored engineering sprint. Makes a modeled support slice eligible; no cash recovery is credited.",
        "workdays": 3,
        "leadDays": 3,
        "costCents": 0,
        "resources": {
          "engineering": 360,
          "support": 0,
          "review": 0
        },
        "prerequisites": [],
        "factBasis": "Engineering minutes: recovery-sprint.csv. Workday timing is an added assumption."
      },
      {
        "id": "support-slice",
        "title": "Protect the urgent queue",
        "description": "Plan a capacity-bounded support slice after queue readiness. It consumes the selected tickets' minutes, not invented money.",
        "workdays": 2,
        "leadDays": 2,
        "costCents": 0,
        "resources": {
          "engineering": 0,
          "support": "selected-ticket-minutes",
          "review": 0
        },
        "prerequisites": [
          "queue-repair"
        ],
        "factBasis": "Ticket estimates and support cap: seed data. Allocation timing and selected slice size are assumptions."
      },
      {
        "id": "contractor-cut",
        "title": "Narrow contractor scope",
        "description": "Assumed agreement lowers a future full cycle from $3,000 to $1,500. Current-cycle obligations survive.",
        "workdays": 1,
        "leadDays": 14,
        "costCents": 30000,
        "resources": {
          "engineering": 0,
          "support": 0,
          "review": 60
        },
        "prerequisites": [],
        "consentKey": "contractorConsent",
        "factBasis": "Rate levels: scenarios.csv. $300 sunk fee, 14-day lead and resource load are assumptions."
      },
      {
        "id": "hosting-cut",
        "title": "Validate smaller hosting",
        "description": "Assumed validation lowers a future full cycle from $1,800 to $1,600, competing with engineering work.",
        "workdays": 2,
        "leadDays": 10,
        "costCents": 45000,
        "resources": {
          "engineering": 120,
          "support": 0,
          "review": 30
        },
        "prerequisites": [],
        "consentKey": "hostingValidated",
        "factBasis": "Rate levels: scenarios.csv. $450 sunk fee, 10-day lead and resource load are assumptions."
      },
      {
        "id": "receipt-pull",
        "title": "Coordinate earlier receipts",
        "description": "Moves part of the same receipt pool ten days earlier; never adds revenue. Uses support and review capacity.",
        "workdays": 2,
        "leadDays": 7,
        "costCents": 15000,
        "resources": {
          "engineering": 0,
          "support": 90,
          "review": 60
        },
        "prerequisites": [],
        "consentKey": "receiptConsent",
        "factBasis": "No timing improvement is in the seed. Fee, share, lead, consent and capacity are added assumptions."
      },
      {
        "id": "defer-payable",
        "title": "Defer prior support bill",
        "description": "Moves $2,500 to day 40 if ready before day 10. Keeps the full reserve, adds a fee and removes support capacity.",
        "workdays": 1,
        "leadDays": 3,
        "costCents": 10000,
        "resources": {
          "engineering": 0,
          "support": 0,
          "review": 60
        },
        "prerequisites": [],
        "consentKey": "deferralConsent",
        "factBasis": "Original $2,500 obligation and date: payables.csv. Every deferral term is an added assumption."
      }
    ],
    "deferral": {
      "payableId": "arrears-support",
      "days": 30,
      "feeCents": 12500,
      "lostSupportMinutes": 120
    },
    "receiptAdvanceDays": 10
  },
  "provenance": {
    "attribution": "projects/08-turnaround/data/attribution.json",
    "copiedData": [
      {
        "local": "data/reference/LICENSE",
        "source": "LICENSE",
        "sha256": "3ca4ef7120c79e55fa3c113f2c6366a072b685018d2bf736ff2bcfceba57a77f"
      },
      {
        "local": "data/reference/recovery.json",
        "source": "templates/casework/work/starter/case/recovery.json",
        "sha256": "92e6b5c0763d226a71996ce9654b43c7e31e7d035d1144b1f97a6b9e37116350"
      },
      {
        "local": "data/reference/cash-ledger.csv",
        "source": "templates/casework/work/starter/data/cash-ledger.csv",
        "sha256": "17728ba9a34df12dcd0997dad08ec922babc3d6d504c2e47e1ab0ac3aad69d8e"
      },
      {
        "local": "data/reference/payables.csv",
        "source": "templates/casework/work/starter/data/payables.csv",
        "sha256": "07c963d545bc10b7a34b78065653ff4c070d8bd9ac0f61991bb7854cf0bf9f31"
      },
      {
        "local": "data/reference/subscriptions.csv",
        "source": "templates/casework/work/starter/data/subscriptions.csv",
        "sha256": "177b247ac08ada48652d2123af4066c946c89e2aeccb367c669d34912ef7ace8"
      },
      {
        "local": "data/reference/scenarios.csv",
        "source": "templates/casework/work/starter/data/scenarios.csv",
        "sha256": "e81fd022a31c2550dd0a54e754d072ad5b7ca164adf57e8bfd9c3214891e2c19"
      },
      {
        "local": "data/reference/support-backlog.csv",
        "source": "templates/casework/work/starter/data/support-backlog.csv",
        "sha256": "565b646c0dbab4567c30838950093b1bf68f3c7332933eddb49c4b40c3027031"
      },
      {
        "local": "data/reference/recovery-sprint.csv",
        "source": "templates/casework/work/starter/ops/recovery-sprint.csv",
        "sha256": "056db98cad94ab00478eb6d37e61c236883b46506c700eca2609ca6755e4c51d"
      },
      {
        "local": "data/reference/approval-gates.json",
        "source": "templates/casework/work/starter/ops/approval-gates.json",
        "sha256": "6e2e89930421dc3b1ab4b0a2b8fb80f8bb31e79e249fd77504ecbaaa6ea69fdf"
      }
    ],
    "modelAssumptionsSha256": "bd1c39b26f8c98724d458cf045b810a003455e906c1d80c8253703c65f261375",
    "scenarioSpecificationSha256": "fa0ac52ebce67adb4f38e16aaae6aa91f5c752d4ebc097f53ac58cbc7e215a90"
  }
};
export const EXPERIMENTS = {
  "schema": "turnaround-scenarios/1",
  "classification": "ADDED MODEL EXPERIMENTS, NOT OBSERVATIONS",
  "scenarios": [
    {
      "id": "baseline",
      "title": "No intervention",
      "useCandidate": false,
      "assumptions": {},
      "description": "Repeated September amounts with no action, date-lumped payments and full prior-payable reserves."
    },
    {
      "id": "recovery",
      "title": "Bounded recovery candidate",
      "useCandidate": true,
      "assumptions": {},
      "description": "Best of the documented finite strategy grid, not a guarantee or a global optimum."
    },
    {
      "id": "delayed-receipts",
      "title": "Receipts +10 days",
      "useCandidate": true,
      "assumptions": {
        "receiptDelayDays": 10
      },
      "description": "Every candidate receipt moves ten days; cycle totals are conserved, including beyond-horizon receivables."
    },
    {
      "id": "weaker-demand",
      "title": "Demand −20%",
      "useCandidate": true,
      "assumptions": {
        "demandBps": 8000
      },
      "description": "Only 80% of the assumed September receipt pool remains each cycle, with unchanged payroll and refunds."
    },
    {
      "id": "combined-stress",
      "title": "Delay + weaker demand",
      "useCandidate": true,
      "assumptions": {
        "receiptDelayDays": 10,
        "demandBps": 8000
      },
      "description": "The same candidate, not re-optimized: both ten-day receipt delay and 20% lower demand."
    }
  ],
  "search": {
    "description": "All 64 subsets of six actions under each of two fixed start schedules: 128 candidates, including empty plans. Default 300-minute support request. Reject prerequisite, due-date, total-budget and daily-capacity violations before scoring. Nothing here authorizes the seed's blocked work.",
    "ranking": [
      "latest strict cash-floor breach (censored at horizon + 1)",
      "latest first unfunded payment (censored at horizon + 1)",
      "most prospective urgent tickets selected",
      "highest end scheduled cash",
      "lowest sunk fees",
      "stable strategy id"
    ],
    "schedules": [
      {
        "id": "early",
        "starts": {
          "queue-repair": 1,
          "support-slice": 6,
          "contractor-cut": 1,
          "hosting-cut": 1,
          "receipt-pull": 1,
          "defer-payable": 1
        }
      },
      {
        "id": "staged",
        "starts": {
          "queue-repair": 5,
          "support-slice": 10,
          "contractor-cut": 8,
          "hosting-cut": 8,
          "receipt-pull": 8,
          "defer-payable": 5
        }
      }
    ],
    "thresholdScan": {
      "receiptDelayDays": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14
      ],
      "demandBps": [
        10000,
        9000,
        8000,
        7000
      ]
    },
    "limitations": [
      "Only two start schedules and six authored actions; no continuous optimization.",
      "The best-scoring policy can still fail the floor and run out of cash.",
      "Consent and physical feasibility of every modeled intervention are unverified.",
      "Delayed receipts and weaker demand do not trigger a new search or a hidden rescue."
    ]
  }
};
export const STUDY = {
  "candidate": {
    "id": "early-010111",
    "plan": [
      {
        "id": "queue-repair",
        "startDay": 1
      },
      {
        "id": "support-slice",
        "startDay": 6
      },
      {
        "id": "contractor-cut",
        "startDay": 1
      },
      {
        "id": "receipt-pull",
        "startDay": 1
      }
    ],
    "actionPlanFeasible": true,
    "floorMaintained": false,
    "cashFundedThroughHorizon": false,
    "recoveryExistsWithinHorizon": false,
    "firstFloorDay": 58,
    "firstUnfundedDay": 90,
    "earliestWarningDay": 0,
    "floorEscalationDay": 51,
    "fundingEscalationDay": 83,
    "finalScheduledCashCents": 245000,
    "finalAvailableCents": 245000,
    "finalPriorPayableReserveCents": 0,
    "minimumCashCents": -262500,
    "minimumAvailableCents": -262500,
    "minimumFloorHeadroomCents": -1462500,
    "receiptsWithinHorizonCents": 4350000,
    "outflowsWithinHorizonCents": 7345000,
    "scheduledActionCostsCents": 45000,
    "endingCycleRecurringBurnCents": 750000,
    "urgentTicketsProspectivelySelected": 3,
    "supportMinutes": 300,
    "issues": []
  },
  "evaluatedCount": 128,
  "validCount": 49,
  "rejectedCount": 79,
  "floorAndFundingSurvivors": 0,
  "scenarios": [
    {
      "id": "baseline",
      "title": "No intervention",
      "summary": {
        "actionPlanFeasible": true,
        "floorMaintained": false,
        "cashFundedThroughHorizon": false,
        "recoveryExistsWithinHorizon": false,
        "firstFloorDay": 28,
        "firstUnfundedDay": 59,
        "earliestWarningDay": 0,
        "floorEscalationDay": 21,
        "fundingEscalationDay": 52,
        "finalScheduledCashCents": -10000,
        "finalAvailableCents": -10000,
        "finalPriorPayableReserveCents": 0,
        "minimumCashCents": -1460000,
        "minimumAvailableCents": -1460000,
        "minimumFloorHeadroomCents": -2660000,
        "receiptsWithinHorizonCents": 4350000,
        "outflowsWithinHorizonCents": 7600000,
        "scheduledActionCostsCents": 0,
        "endingCycleRecurringBurnCents": 900000,
        "urgentTicketsProspectivelySelected": 0,
        "supportMinutes": 0
      }
    },
    {
      "id": "recovery",
      "title": "Bounded recovery candidate",
      "summary": {
        "actionPlanFeasible": true,
        "floorMaintained": false,
        "cashFundedThroughHorizon": false,
        "recoveryExistsWithinHorizon": false,
        "firstFloorDay": 58,
        "firstUnfundedDay": 90,
        "earliestWarningDay": 0,
        "floorEscalationDay": 51,
        "fundingEscalationDay": 83,
        "finalScheduledCashCents": 245000,
        "finalAvailableCents": 245000,
        "finalPriorPayableReserveCents": 0,
        "minimumCashCents": -262500,
        "minimumAvailableCents": -262500,
        "minimumFloorHeadroomCents": -1462500,
        "receiptsWithinHorizonCents": 4350000,
        "outflowsWithinHorizonCents": 7345000,
        "scheduledActionCostsCents": 45000,
        "endingCycleRecurringBurnCents": 750000,
        "urgentTicketsProspectivelySelected": 3,
        "supportMinutes": 300
      }
    },
    {
      "id": "delayed-receipts",
      "title": "Receipts +10 days",
      "summary": {
        "actionPlanFeasible": true,
        "floorMaintained": false,
        "cashFundedThroughHorizon": false,
        "recoveryExistsWithinHorizon": false,
        "firstFloorDay": 28,
        "firstUnfundedDay": 59,
        "earliestWarningDay": 0,
        "floorEscalationDay": 21,
        "fundingEscalationDay": 52,
        "finalScheduledCashCents": -262500,
        "finalAvailableCents": -262500,
        "finalPriorPayableReserveCents": 0,
        "minimumCashCents": -1205000,
        "minimumAvailableCents": -1205000,
        "minimumFloorHeadroomCents": -2405000,
        "receiptsWithinHorizonCents": 3842500,
        "outflowsWithinHorizonCents": 7345000,
        "scheduledActionCostsCents": 45000,
        "endingCycleRecurringBurnCents": 750000,
        "urgentTicketsProspectivelySelected": 3,
        "supportMinutes": 300
      }
    },
    {
      "id": "weaker-demand",
      "title": "Demand −20%",
      "summary": {
        "actionPlanFeasible": true,
        "floorMaintained": false,
        "cashFundedThroughHorizon": false,
        "recoveryExistsWithinHorizon": false,
        "firstFloorDay": 30,
        "firstUnfundedDay": 88,
        "earliestWarningDay": 0,
        "floorEscalationDay": 23,
        "fundingEscalationDay": 81,
        "finalScheduledCashCents": -625000,
        "finalAvailableCents": -625000,
        "finalPriorPayableReserveCents": 0,
        "minimumCashCents": -1031000,
        "minimumAvailableCents": -1031000,
        "minimumFloorHeadroomCents": -2231000,
        "receiptsWithinHorizonCents": 3480000,
        "outflowsWithinHorizonCents": 7345000,
        "scheduledActionCostsCents": 45000,
        "endingCycleRecurringBurnCents": 1040000,
        "urgentTicketsProspectivelySelected": 3,
        "supportMinutes": 300
      }
    },
    {
      "id": "combined-stress",
      "title": "Delay + weaker demand",
      "summary": {
        "actionPlanFeasible": true,
        "floorMaintained": false,
        "cashFundedThroughHorizon": false,
        "recoveryExistsWithinHorizon": false,
        "firstFloorDay": 28,
        "firstUnfundedDay": 58,
        "earliestWarningDay": 0,
        "floorEscalationDay": 21,
        "fundingEscalationDay": 51,
        "finalScheduledCashCents": -1031000,
        "finalAvailableCents": -1031000,
        "finalPriorPayableReserveCents": 0,
        "minimumCashCents": -1785000,
        "minimumAvailableCents": -1785000,
        "minimumFloorHeadroomCents": -2985000,
        "receiptsWithinHorizonCents": 3074000,
        "outflowsWithinHorizonCents": 7345000,
        "scheduledActionCostsCents": 45000,
        "endingCycleRecurringBurnCents": 1040000,
        "urgentTicketsProspectivelySelected": 3,
        "supportMinutes": 300
      }
    }
  ],
  "thresholds": [
    {
      "demandBps": 10000,
      "receiptDelayDays": 0,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": 245000,
      "finalAvailableCents": 245000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 4350000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 1,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 2,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 3,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 4,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 5,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 6,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 7,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 58,
      "firstUnfundedDay": 90,
      "earliestWarningDay": 0,
      "floorEscalationDay": 51,
      "fundingEscalationDay": 83,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -262500,
      "minimumAvailableCents": -262500,
      "minimumFloorHeadroomCents": -1462500,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 8,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -705000,
      "minimumAvailableCents": -705000,
      "minimumFloorHeadroomCents": -1905000,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 9,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -855000,
      "minimumAvailableCents": -855000,
      "minimumFloorHeadroomCents": -2055000,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 10,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -262500,
      "finalAvailableCents": -262500,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1205000,
      "minimumAvailableCents": -1205000,
      "minimumFloorHeadroomCents": -2405000,
      "receiptsWithinHorizonCents": 3842500,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 11,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -1205000,
      "finalAvailableCents": -1205000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1205000,
      "minimumAvailableCents": -1205000,
      "minimumFloorHeadroomCents": -2405000,
      "receiptsWithinHorizonCents": 2900000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 12,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -1205000,
      "finalAvailableCents": -1205000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1205000,
      "minimumAvailableCents": -1205000,
      "minimumFloorHeadroomCents": -2405000,
      "receiptsWithinHorizonCents": 2900000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 13,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -1205000,
      "finalAvailableCents": -1205000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1205000,
      "minimumAvailableCents": -1205000,
      "minimumFloorHeadroomCents": -2405000,
      "receiptsWithinHorizonCents": 2900000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 10000,
      "receiptDelayDays": 14,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 59,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 52,
      "finalScheduledCashCents": -1205000,
      "finalAvailableCents": -1205000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1205000,
      "minimumAvailableCents": -1205000,
      "minimumFloorHeadroomCents": -2405000,
      "receiptsWithinHorizonCents": 2900000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 750000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 0,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -190000,
      "finalAvailableCents": -190000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3915000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 1,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 2,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 3,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 4,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 5,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 6,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 7,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -646750,
      "minimumAvailableCents": -646750,
      "minimumFloorHeadroomCents": -1846750,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 8,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -995000,
      "minimumAvailableCents": -995000,
      "minimumFloorHeadroomCents": -2195000,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 9,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1145000,
      "minimumAvailableCents": -1145000,
      "minimumFloorHeadroomCents": -2345000,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 10,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -646750,
      "finalAvailableCents": -646750,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1495000,
      "minimumAvailableCents": -1495000,
      "minimumFloorHeadroomCents": -2695000,
      "receiptsWithinHorizonCents": 3458250,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 11,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1495000,
      "finalAvailableCents": -1495000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1495000,
      "minimumAvailableCents": -1495000,
      "minimumFloorHeadroomCents": -2695000,
      "receiptsWithinHorizonCents": 2610000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 12,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1495000,
      "finalAvailableCents": -1495000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1495000,
      "minimumAvailableCents": -1495000,
      "minimumFloorHeadroomCents": -2695000,
      "receiptsWithinHorizonCents": 2610000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 13,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1495000,
      "finalAvailableCents": -1495000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1495000,
      "minimumAvailableCents": -1495000,
      "minimumFloorHeadroomCents": -2695000,
      "receiptsWithinHorizonCents": 2610000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 9000,
      "receiptDelayDays": 14,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1495000,
      "finalAvailableCents": -1495000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1495000,
      "minimumAvailableCents": -1495000,
      "minimumFloorHeadroomCents": -2695000,
      "receiptsWithinHorizonCents": 2610000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 895000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 0,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -625000,
      "finalAvailableCents": -625000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3480000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 1,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 2,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 3,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 4,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 5,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 6,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 7,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 88,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 81,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1031000,
      "minimumAvailableCents": -1031000,
      "minimumFloorHeadroomCents": -2231000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 8,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1285000,
      "minimumAvailableCents": -1285000,
      "minimumFloorHeadroomCents": -2485000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 9,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1435000,
      "minimumAvailableCents": -1435000,
      "minimumFloorHeadroomCents": -2635000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 10,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1031000,
      "finalAvailableCents": -1031000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1785000,
      "minimumAvailableCents": -1785000,
      "minimumFloorHeadroomCents": -2985000,
      "receiptsWithinHorizonCents": 3074000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 11,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1785000,
      "finalAvailableCents": -1785000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1785000,
      "minimumAvailableCents": -1785000,
      "minimumFloorHeadroomCents": -2985000,
      "receiptsWithinHorizonCents": 2320000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 12,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1785000,
      "finalAvailableCents": -1785000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1785000,
      "minimumAvailableCents": -1785000,
      "minimumFloorHeadroomCents": -2985000,
      "receiptsWithinHorizonCents": 2320000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 13,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1785000,
      "finalAvailableCents": -1785000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1785000,
      "minimumAvailableCents": -1785000,
      "minimumFloorHeadroomCents": -2985000,
      "receiptsWithinHorizonCents": 2320000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 8000,
      "receiptDelayDays": 14,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1785000,
      "finalAvailableCents": -1785000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1785000,
      "minimumAvailableCents": -1785000,
      "minimumFloorHeadroomCents": -2985000,
      "receiptsWithinHorizonCents": 2320000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1040000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 0,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1060000,
      "finalAvailableCents": -1060000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 3045000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 1,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 2,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 3,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 4,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 5,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 6,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 7,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 30,
      "firstUnfundedDay": 60,
      "earliestWarningDay": 0,
      "floorEscalationDay": 23,
      "fundingEscalationDay": 53,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1415250,
      "minimumAvailableCents": -1415250,
      "minimumFloorHeadroomCents": -2615250,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 8,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1575000,
      "minimumAvailableCents": -1575000,
      "minimumFloorHeadroomCents": -2775000,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 9,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -1725000,
      "minimumAvailableCents": -1725000,
      "minimumFloorHeadroomCents": -2925000,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 10,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -1415250,
      "finalAvailableCents": -1415250,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -2075000,
      "minimumAvailableCents": -2075000,
      "minimumFloorHeadroomCents": -3275000,
      "receiptsWithinHorizonCents": 2689750,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 11,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -2075000,
      "finalAvailableCents": -2075000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -2075000,
      "minimumAvailableCents": -2075000,
      "minimumFloorHeadroomCents": -3275000,
      "receiptsWithinHorizonCents": 2030000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 12,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -2075000,
      "finalAvailableCents": -2075000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -2075000,
      "minimumAvailableCents": -2075000,
      "minimumFloorHeadroomCents": -3275000,
      "receiptsWithinHorizonCents": 2030000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 13,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -2075000,
      "finalAvailableCents": -2075000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -2075000,
      "minimumAvailableCents": -2075000,
      "minimumFloorHeadroomCents": -3275000,
      "receiptsWithinHorizonCents": 2030000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    },
    {
      "demandBps": 7000,
      "receiptDelayDays": 14,
      "actionPlanFeasible": true,
      "floorMaintained": false,
      "cashFundedThroughHorizon": false,
      "recoveryExistsWithinHorizon": false,
      "firstFloorDay": 28,
      "firstUnfundedDay": 58,
      "earliestWarningDay": 0,
      "floorEscalationDay": 21,
      "fundingEscalationDay": 51,
      "finalScheduledCashCents": -2075000,
      "finalAvailableCents": -2075000,
      "finalPriorPayableReserveCents": 0,
      "minimumCashCents": -2075000,
      "minimumAvailableCents": -2075000,
      "minimumFloorHeadroomCents": -3275000,
      "receiptsWithinHorizonCents": 2030000,
      "outflowsWithinHorizonCents": 7345000,
      "scheduledActionCostsCents": 45000,
      "endingCycleRecurringBurnCents": 1185000,
      "urgentTicketsProspectivelySelected": 3,
      "supportMinutes": 300
    }
  ]
};
