#!/usr/bin/env python3
"""Build/check the deterministic offline bundle and local integrity receipt. No network."""

import argparse
import hashlib
import json
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]


def sha(data):
    return hashlib.sha256(data).hexdigest()


def read_json(path):
    return json.loads((PROJECT / path).read_text())


def outputs():
    research = read_json("research/evidence.json")
    protocol_bytes = (PROJECT / "research/protocol.json").read_bytes()
    lock = read_json("research/protocol-lock.json")
    if sha(protocol_bytes) != lock["sha256"]:
        raise ValueError("Locked pre-collection protocol changed")
    captures, capture_hashes = {}, {}
    for source in research["sources"]:
        raw = (PROJECT / source["capture"]).read_bytes()
        captures[source["id"]] = json.loads(raw)
        capture_hashes[source["id"]] = sha(raw)
    bundle = {
        "research": research,
        "protocol": json.loads(protocol_bytes),
        "captures": captures,
        "receipt": {
            "protocolSha256": sha(protocol_bytes),
            "researchSha256": sha((PROJECT / "research/evidence.json").read_bytes()),
            "sourceCaptureSha256": capture_hashes,
        },
    }
    payload = json.dumps(bundle, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    javascript = ("// Generated by tools/build.py from inspected local JSON; no runtime fetch.\n"
                  + "globalThis.INTELLIGENCE_DATA = " + payload + ";\n").encode()
    inventory = []
    excluded = {"data.js", "evidence/integrity.json", "evidence/result.json"}
    for path in sorted(PROJECT.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        relative = path.relative_to(PROJECT).as_posix()
        if relative in excluded or relative.startswith("evidence/test-output/"):
            continue
        raw = path.read_bytes()
        inventory.append({"path": relative, "bytes": len(raw), "sha256": sha(raw)})
    inventory.append({"path": "data.js", "bytes": len(javascript), "sha256": sha(javascript)})
    inventory.sort(key=lambda item: item["path"])
    integrity = {
        "schema": "local-research-integrity/1",
        "algorithm": "SHA-256",
        "scope": "Project artifacts only. Result/command transcripts and this self-referential receipt are excluded. Remote full-body hashes attest fetched bytes but cannot reproduce a changing web page without its archive.",
        "files": inventory,
    }
    return {"data.js": javascript, "evidence/integrity.json": (json.dumps(integrity, indent=2) + "\n").encode()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Compare without writing")
    args = parser.parse_args()
    for relative, data in outputs().items():
        path = PROJECT / relative
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit("STALE or missing: " + relative + "; run python3 projects/03-intelligence/tools/build.py")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print("PASS: offline bundle and integrity receipt are deterministic and current." if args.check
          else "Built offline data.js and evidence/integrity.json from local inputs only.")


if __name__ == "__main__":
    main()
